Feat/merge/meta noindex
opendatateam/udata-front-kit pull request #508
Opened 2024-08-26 18:38 UTC by narduin

Ajout de la balise meta noindex pour les versions non `prod`.
Modification de la config afin d'empêcher robots.txt d'être en disallow, [ce qui peut empêcher la meta d'être respectée.](https://developers.google.com/search/docs/crawling-indexing/block-indexing?hl=fr) Je n

Fix https://github.com/ecolabdata/ecospheres/issues/222

2024-09-02 15:58 UTC, abulte commented
@narduin tu as besoin de plus d'infos là-dessus ? J'ai l'impression que la description de la PR est tronquée : "Je n"... Suspense ! ;-)

2024-09-03 15:29 UTC, narduin commented
> @narduin tu as besoin de plus d'infos là-dessus ? J'ai l'impression que la description de la PR est tronquée : "Je n"... Suspense ! ;-)

Effectivement il manque la fin !
Je ne suis pas certain de savoir comment fonctionne la config en prod. Il faudrait peut-être ajouter un `Allow` plutôt que de laisser vide le robots.txt

2024-09-03 16:07 UTC, abulte commented
En prod ça donne ça (généré à partir de la conf https://github.com/opendatateam/udata-front-kit/blob/6dacfcd866d40ad66e4b2f52d01b569f8ac114d2/configs/ecospheres/config.yaml#L17) https://ecologie.data.gouv.fr/robots.txt

Pas besoin de `Allow` je pense. Peut-être qu'il faudra utiliser des noindex plutôt que des disallow pour admin & co d'ailleurs (mais je ne crois pas que ça pose problème pour l'instant).

Sur la PR en cours : il va manquer les autres pages, genre jeux de données ou autre. Est-ce que ne peut pas injecter un `noindex,nofollow` directement depuis dans le index.html via le build ? Ca permettra de couvrir toutes les pages d'un coup.

2024-09-05 07:26 UTC, narduin commented
> Sur la PR en cours : il va manquer les autres pages, genre jeux de données ou autre. Est-ce que ne peut pas injecter un `noindex,nofollow` directement depuis dans le index.html via le build ? Ca permettra de couvrir toutes les pages d'un coup.

J'ai ajouté la `meta` dans le vite.config comme ça tout le site est couvert c'est plus propre oui.

2024-09-05 08:53 UTC, abulte reviewed
Plus propre en effet 👍 

Niveau config :
- Il faut penser à mettre à jour les fichiers de conf pour notre site et les autres si tu ajoutes une nouvelle clé.
- Est-ce que ça vaut le coup de gérer un `env` juste pour ça ? Je mettrais bien directement la chaine `index, follow` ou `noindex, nofollow` dans une clé de conf `robots.meta`. @streino

2024-09-05 09:12 UTC, narduin commented
Mince je croyais qu'il y avait déjà la clé dans la conf.
Est-ce qu'on peut utiliser `process.env.NODE_ENV === 'production'` à la place ?
J'imagine que même sur `demo.ecologie` on est en production donc il faudrait personnaliser la variable quoiqu'il arrive (dans la conf ou dans .env)

2024-09-05 09:18 UTC, abulte commented
Oui sur demo.ecologie on sera considéré comme en prod, donc NODE_ENV ne sera pas utile. D'où l'idée de gérer directement la chaine sans passer par une indirection `env` : quitte à gérer une configuration par env autant la gérer la plus explicitement possible.

2024-09-12 18:24 UTC, streino commented
>     * Est-ce que ça vaut le coup de gérer un `env` juste pour ça ? Je mettrais bien directement la chaine `index, follow` ou `noindex, nofollow` dans une clé de conf `robots.meta`. @streino

Désolé, la notif était passée à la trappe...
La proposion d'@abulte me semble plus en phase avec ce qu'on fait déjà, à savoir mettre un max dans la config. Il y a un autre enjeu sur cette décision ?

2024-09-12 18:26 UTC, abulte commented
Non pas d'autre enjeu. Go pour la chaîne en conf !

2024-09-17 14:08 UTC, abulte commented
@narduin c'est clair pour toi ?

2024-09-17 15:42 UTC, narduin commented
> @narduin c'est clair pour toi ?

Oui je vais ajouter les conf !

2024-09-17 16:14 UTC, abulte reviewed
Il manque la conf pour le site `defis`

2024-09-17 16:18 UTC, narduin commented
> Il manque la conf pour le site `defis`

J'étais persuadé qu'il n'y avait que 3 sites désolé

2024-09-17 16:20 UTC, abulte approved these changes

2024-09-17 16:21 UTC, abulte commented
@streino c'est quoi le process pour mettre à jour les configs de prod et démo déjà ? On gère au moment des déploiements ?

2024-09-18 07:46 UTC, streino commented
Pour les branches de déploiement qui ont besoin de modifs, le mieux c'est de faire une PR visant la branche en question. Sinon on peut gérer au moment du déploiement mais faut pas oublier de le faire. L'"avantage" de la PR maintenant étant que ça créera un conflit plus tard, donc moins de risque d'oubli ;)

Là si je ne m'abuse, les modifs en `main` vont être propagées telles quelles sur `ecospheres-demo`, donc rien à faire. Donc PR spécifique sur `ecospheres-prod` ?

Il faut probablement aussi tenir data.gouv au courant pour les autres verticales ?

2024-09-18 07:49 UTC, abulte commented
> Là si je ne m'abuse, les modifs en main vont être propagées telles quelles sur ecospheres-demo, donc rien à faire. Donc PR spécifique sur ecospheres-prod ?

Oui. @narduin tu te sens de la faire ?

> Il faut probablement aussi tenir data.gouv au courant pour les autres verticales ?

Pas vraiment d'impact, les autres verticales sont en `index, follow`, qu'on peut considérer comme le défaut. Ping @geoffreyaldebert quand même :-)

2024-09-18 08:48 UTC, narduin commented
> Pas vraiment d'impact, les autres verticales sont en `index, follow`

J'avais effectivement mis du `index, follow` au départ puis je me suis rendu compte hier que tout le monde avait un `Disallow /` avant. Est-ce que je mets tout en noindex ?

2024-09-18 13:28 UTC, abulte commented
Effectivement (e.g. https://meteo.data.gouv.fr/robots.txt)... Pas sûr que ce soit ce que veut @geoffreyaldebert en revanche :-)

<img width="449" alt="Capture d’écran 2024-09-18 à 15 26 55" src="https://github.com/user-attachments/assets/3824ff14-5863-434f-a292-48ecf2addc21">

Pour rester cohérent, passons en `noindex`. @geoffreyaldebert tu as la recette ici si tu veux activer l'indexation de tes sites.

2024-09-19 12:13 UTC, abulte requested changes
J'enlève le "approved" le temps que tu puisses faire le changement `noindex` pour les autre sites @narduin.

2024-09-23 12:56 UTC, abulte approved these changes

2024-09-24 09:04 UTC, DanFluture275 approved these changes
Testé PO

2024-09-24 11:11 UTC, DanFluture275 approved these changes
Testé PO OK

2024-09-24 11:45 UTC, merged