remove: oauth variables from config and put it to .env
opendatateam/udata-front-kit pull request #511
Opened 2024-08-30 07:50 UTC by geoffreyaldebert

2024-08-30 08:13 UTC, geoffreyaldebert commented
ok pour faire passer les tests j'ai ajouter les variables du .env [ici](https://github.com/opendatateam/udata-front-kit/settings/variables/actions) et[ici](https://github.com/opendatateam/udata-front-kit/settings/secrets/actions)

2024-08-30 09:32 UTC, streino approved these changes
J'ai fait la modif sur Netlify pour écosphères.
On deploy aussi meteo, je vois pas de clé, il en faudra une ?

Pour les tests, on continue d'utiliser la clé écosphères ou on en profite pour en créer une dédiée aux tests ?

2024-08-30 09:35 UTC, streino reviewed
Penser à mettre à jour la section config du README comme les vars ne sont plus dans la config.

2024-08-30 09:37 UTC, streino requested changes
Penser à mettre à jour la section config du README comme les vars ne sont plus dans la config.

2024-08-30 10:44 UTC, geoffreyaldebert commented
No pb c'est fait :)

2024-08-30 10:45 UTC, geoffreyaldebert commented
il faudra une clé sur meteo je te la filerai quand je l'aurai :)

2024-08-30 10:59 UTC, streino approved these changes

2024-08-30 10:59 UTC, streino commented on configs/defis/config.yaml
> +themes:
La suppression de la première ligne du commentaire, c'est voulu ?

2024-08-30 10:59 UTC, streino commented on configs/ecospheres/config.yaml
> -  # oauth settings
Les clés seront encore dans l'historique du repo. C'est relou à purger, donc si c'est un problème mieux vaut peut-être changer les clés existantes ?

2024-09-02 07:49 UTC, geoffreyaldebert commented on configs/ecospheres/config.yaml
> -  # oauth settings
oui je pense qu'on va les changer du coup

2024-09-02 07:49 UTC, geoffreyaldebert commented on configs/defis/config.yaml
> +themes:
non je corrige

2024-09-02 07:59 UTC, abulte commented
👋 

Je ne vois pas trop l'intérêt de cette modification, sachant que les credentials sont triviales à récupérer depuis le code Javascript ou l'inspection des requêtes réseau.

L'idée originale derrière le `.env` était de stocker uniquement un id de site et de garder l'intégralité de la conf dans un fichier spécifique au site.

En revanche je comprends que ce soit choquant de stocker un secret (qui n'en est pas un) dans le repo. J'ai refait quelques recherches et j'ai peut-être une solution plus propre : on a pas besoin de secret dans un client oauth qui sera utilisé par une SPA. Udata ne le supporte pas actuellement mais j'ai commencé une PR pour l'ajouter, j'envoie ça dans la journée.

On pourrait donc se débarrasser du secret dans ce repo, et donc garder l'id dans la conf ?

2024-09-02 08:02 UTC, geoffreyaldebert commented
effectivement si on ne fait pas comme ça il faut faire une modification à udata. Perso je préfère éviter que ces ids trainent sur le code, c'est quand même plus obvious que dans le build js. Donc si pas de solution côté udata, je veux bien maintenir cette solution quand même. Mais ok tu nous ping quand tu as quelque chose et on peut laisser cette solution en draft, je ne la merge pas.

2024-09-02 14:25 UTC, abulte commented
https://github.com/opendatateam/udata/pull/3138

Je fais une PR ici aussi pour supprimer le secret de la conf et des calls API.

2024-09-02 14:30 UTC, abulte commented
https://github.com/opendatateam/udata-front-kit/pull/514

2024-09-20 15:20 UTC, closed without merging